version: '3'

services:
  app:
    # build the mage before the start or use already built
    # DOCKER_BUILDKIT=0 docker build -t onomy/big-dipper:local .
    image: onomy/big-dipper:latest
    restart: on-failure
    ports:
      - '3080:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS: ${METEOR_SETTINGS}

  mongo:
    image: mongo:latest
    restart: on-failure
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
